import argparse
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

try:
    from .roi_calculator import ROIInputs, compute_roi
except ImportError:  # pragma: no cover - fallback for direct execution
    from roi_calculator import ROIInputs, compute_roi


@dataclass
class WorkshopInputs:
    company: str
    use_case: str
    users: str
    data_sources: str
    constraints: str
    success_metrics: str


def _defaults() -> WorkshopInputs:
    return WorkshopInputs(
        company="Hypothetical Enterprise",
        use_case="Support deflection + incident triage",
        users="Support agents, SRE, security reviewers",
        data_sources="Ticket system, runbooks, handover docs",
        constraints="PII handling, auditability, latency < 3s",
        success_metrics="Deflection rate, CSAT delta, MTTR reduction",
    )


def generate_workshop_bundle(output_dir: Path, inputs: WorkshopInputs) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)

    brief_path = output_dir / "discovery_brief.md"
    brief_path.write_text(
        f"""# Discovery Brief (Sample Output)

Note: This is a synthetic, portfolio-only output. No real customer data is included.

- Company: {inputs.company}
- Use case: {inputs.use_case}
- Users: {inputs.users}

## Data Sources
{inputs.data_sources}

## Constraints
{inputs.constraints}

## Success Metrics
{inputs.success_metrics}
"""
    )

    eval_plan_path = output_dir / "eval_plan.md"
    eval_plan_path.write_text(
        """# Draft Eval Plan (Sample Output)

Note: This is a synthetic, portfolio-only output generated by the workshop script.

## Dataset Fields
- id, use_case, input, expected(optional), role, sensitivity

## Rubric (1-5)
- Accuracy
- Groundedness
- Helpfulness
- Safety

## Baseline
- initial_20 + sample/synthetic set

## Regression
- Compare against last baseline report
"""
    )

    roi_inputs = ROIInputs(
        handle_time_minutes=12,
        tickets_per_week=800,
        hourly_cost=35,
        deflection_rate=0.25,
        adoption_rate=0.6,
        one_time_cost=50000.0,
    )
    roi = compute_roi(roi_inputs)
    roi_path = output_dir / "roi_summary.md"
    roi_path.write_text(
        f"""# ROI Summary

- Weekly savings: {roi['weekly_savings']} USD
- Monthly savings: {roi['monthly_savings']} USD
- Breakeven (months): {roi['breakeven_months']}
"""
    )

    poc_path = output_dir / "poc_success_criteria.md"
    poc_path.write_text(
        """# PoC Success Criteria (Exec Summary)

## Reliability SLOs
- P95 latency < 3.5s
- Error rate < 2%

## Eval Thresholds
- Accuracy >= 3.5/5
- Groundedness >= 3.5/5

## Security Gates
- RBAC enforced
- Redaction verified
- Audit logs enabled

## Rollout Plan
- PoC -> Limited pilot -> Production rollout
"""
    )

    return [brief_path, eval_plan_path, roi_path, poc_path]


def main() -> None:
    defaults = _defaults()
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", default="docs/samples/workshop_output/demo_run")
    parser.add_argument("--company", default=defaults.company)
    parser.add_argument("--use-case", dest="use_case", default=defaults.use_case)
    parser.add_argument("--users", default=defaults.users)
    parser.add_argument("--data-sources", dest="data_sources", default=defaults.data_sources)
    parser.add_argument("--constraints", default=defaults.constraints)
    parser.add_argument("--success-metrics", dest="success_metrics", default=defaults.success_metrics)
    args = parser.parse_args()

    inputs = WorkshopInputs(
        company=args.company,
        use_case=args.use_case,
        users=args.users,
        data_sources=args.data_sources,
        constraints=args.constraints,
        success_metrics=args.success_metrics,
    )

    output_dir = Path(args.output_dir)
    files = generate_workshop_bundle(output_dir, inputs)
    ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
    print(f"Workshop bundle generated at {output_dir} ({ts})")
    for path in files:
        print(f"- {path}")


if __name__ == "__main__":
    main()
